### ISSUE TITLE
How to add design standards to a new Jekyll project?

### ISSUE THREAD

**Issue by bsweger** [18F/us_web_design_standards_gem#12]
Feel free to let me know if, as someone who doesn't use Jekyll, Ruby, or Sass much, I'm not the intended audience, but I have some questions about the directions for using the U.S. design standards with Jekyll.

Basically, I spun up a new Jekyll project by doing `jekyll new SITE-NAME` and would like to use the U.S. design standards assets instead of the default Jekyll styles.

README.md currently states: 

```
Integrate the generated uswds.css file and its styles into your project's layouts and templates, build the site per usual, and observe the results.
```

Where does the generated uswds.css file come from? Is it supposed to show up after the Jekyll build, or is there an intermediate step?

Other questions about using this with a new Jekyll project:
- Can the uswds.scss replace the Jekyll's default main.scss?
- If your Jekyll site is hosted on github pages, will this plugin work, or will you have to generate the pages locally and push the _site folder to Github?

It would be lovely to have some guidance re: spinning up a fresh Jekyll project with the design standards. I'm happy to lend a hand with the documentation if I can figure this out.

**Comment by mbland** [comment]
I've been negligent lately in terms being responsive to issues here due to working on https://pages.18f.gov/unit-testing-node/ (plus the fact that I'm not a Rails dev, and that's been most of the discussion), but hope to be able to jump in and lend a hand on this and other issues soon.

To answer your questions, @bsweger:
- After a `jekyll build` or `jekyll serve`, the generated `uswds.css` file is in the same relative directory under `_site` (where Jekyll places its output by defult) as the one containing `uswds.scss` in the source. For example, if you create `assets/css/uswds.scss` in your source, it will produce `_site/assets/css/uswds.css`.
- `uswds.scss` can replace the default `main.scss`, provided you've updated your `_layouts` and `_includes` and so forth to use it. Or, you can just take the content from the `uswds.scss` example in the README and replace the default contents of `main.scss` with it.
- At the moment, you'd probably have to generate the pages locally and push to `gh-pages`, but we may be able to get the gem whitelisted by GitHub, I'd imagine. On https://pages.18f.gov/, it will work out of the box, since we implicitly trust sites in the 18F organization and don't restrict plugins.

Also, @bsweger, if you'd like to produce documentation, I'd be thrilled, and always happy to lend a hand.

**Comment by bsweger** [comment]
@mbland thanks for the info. Now that I know what's supposed to be happening, I dug in a bit more. 

Though I was able to get the example in the README to work (i.e., the 18F guides template), I wasn't able to successfully use this gem with a brand new Jekyll project. Running `bundle exec jekyll serve` resulted in this error message:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                File to import not found or unreadable: us_web_design_standards. Load path: /Users/rebeccasweger/Dev/testy/_sass on line 1
jekyll 3.0.2 | Error:  File to import not found or unreadable: us_web_design_standards.
Load path: /Users/rebeccasweger/Dev/testy/_sass on line 1
```

The specific steps:
1. Follow the directions here for setting up a new jekyll site/repo: https://help.github.com/articles/using-jekyll-with-pages/
2. Run `bundle exec jekyll server` to make sure I can run the site locally
3. Add `uswds.scss` to the `css`  folder (leaving the default `main.css` in place)
4. Restart the local server and get the error message above

I also tried moving `uswds.scss` to the project's `_sass` folder and was able to get the site running. However, the .css file didn't show up in `_site`.

It would be the bees knees to have this working for an out-of-the-box Jekyll site. Not sure if there's a technical issue or just some additional n00b documentation needed.

If this isn't the intended use case, let me know, and I'll add the design standard assets to the project the old-fashioned way. Thanks again for the help--much appreciated!

**Comment by rogeruiz** [comment]
hey @bsweger, we are starting the process of dog-fooding this gem within the Web Design Standards website, it itself being a Jekyll site too. ( 18F/web-design-standards#978 )

 There's also a big refactor incoming to this gem hopefully sometime today or later this week. ( 18F/web-design-standards#980 )

I'll do my best to cover this issue with updated documentation in this repo for installing in a Jekyll site along with the updating the gem

I'm not sure if Github Pages will allow this Gem to be run on their servers and it might need to be manually pushed / rsynced to be on `gh-pages`.

**Comment by bsweger** [comment]
@rogeruiz wonderful, thanks for the update! Will keep an eye out for the upcoming changes. I like @mbland's suggestion above that it might be possible for Github to whitelist this gem, since manually pushing updates adds friction for non-technical content collaborators.

Very excited about all the work being done to lower the barriers for using the draft web standards. Thank you!

**Comment by emilyville** [comment]
Looking through the above @rogeruiz - I see the PR you referenced above (https://github.com/18F/web-design-standards/pull/980) has been merged. 

Is it still in the works to update this gem? FWIW I'm running into the same error as @bsweger.

**Comment by emilyville** [comment]
Actually got this working! 

Everything is right in the readme, except I didn't need to add a new file called uswds.scss - but rather added a `@import "us_web_design_standards"` to the bottom of my main.scss file and ran `bundle install`. 

Then make sure to run `bundle exec jekyll serve`

:+1:
