### ISSUE TITLE
[ refactor ] As a user of this gem, I would like to be able to consume this gem following the recent refactor of the Draft US Web Design Standards

### ISSUE THREAD

**Issue by rogeruiz** [18F/us_web_design_standards_gem#15]
The Draft US Web Design Standards are going through a major refactoring. In doing so, [the uswds package has also decided to officially support this ruby gem](https://github.com/18F/web-design-standards/blob/18f-pages-staging/Gemfile#L13-L15). This gem is a dependency of the [uswds documentation website](http://playbook.cio.gov/designstandards/). 
### Discussion
1. Keeping track of the file changes for this migration by reference.
2. Discussion around the migration and documentation
3. Discussion around CSS and JS dependencies
### Checklist
- [x] Rename `components.js` to `uswds.js`
- [x] Fully support `Jekyll`
  - [ ] and `Rails`
- [ ] Update the documentation to reflect all of these changes
- [ ] Discuss including jQuery as a dependency for this gem ( _the `uswds` package depends on it_ )

**Comment by rogeruiz** [comment]
@jessieay I'm going to split up #13 into a few branches. Currently, #16 points to merging it's changes into `refactor-gem` which will now be the "`master`" branch for this large set of changes. #16 is still pretty big, but it is solely updating the `assets` directory that is currently on `master`.

**Comment by rogeruiz** [comment]
In regards to that last checklist item: 

Should this be up to the consumer of the gem? _I think that would be better than including it in the bundled JavaScript_. Although, this would require the bundled JS in Draft US Web Design Standards to check for jQuery and not execute any code unless it exists. Currently, the `uswds.js` file does not do this. It would also require the https://github.com/18F/web-design-standards/pull/980 to take this dependency requirement into account since it would need to remove jQuery during the bundling process for `dist-gem`.

**Comment by msecret** [comment]
@rogeruiz I actually tried this on cloud-gov style: https://github.com/18F/cg-style-gem, https://github.com/18F/cg-style/tree/refactor-dependency_overhall. 

You can essentially do almost everything to update the gem with the new assets. So my process is:
- clone gem repo to ./gem
- build assets and copy them to relevant folders in gem
- add all files in ./gem and commit, push them
- publish the gem?

The last step might be a little confusing to set up because you might need a certain login to do it?

**Comment by rogeruiz** [comment]
Currently, we would need update how we support bundling our assets specifically for Rails ( i.e. `image-url`, `asset-url`, folder structure, `src` versus `dist` assets, etc ) since we do not currently have this built into any of the automation workflows in 18f/web-design-standards#980.

I'd love to support Rails with this `gem`, but I'm not sure how many apps will be consuming the standards via Rails. We are focusing our efforts for supporting distribution of the Standards in two distinct ways:
1. `npm` support to locally build the assets within a project, along with Jekyll-only support via this `gem` because the Standards site is built on Jekyll. 
2. Automation workflows which create both source and compiled / bundled assets directories which a developer would need to either build locally using the repository or download via ZIP archive downloads of Releases.
   - **Currently, I'm seeing the future of this `gem` take this route since we're unclear on how much value and effort supporting both Jekyll and Rails within the same `gem` would be.**

Thoughts would be appreciated! Thanks!

cc: @harrisj @msecret @jessieay @pkarman @juliaelman @maya @mbland

**Comment by juliasolorzano** [comment]
I completely agree with @rogeruiz that supporting the gem against Rails is something that needs clarification. It would be good for us to consider where user needs are prior to putting the work into supporting Rails, or any framework for that matter.

However, I do admit that we ARE supporting a framework: Jekyll. This is primarily because it is a tool we have used to help create and test the Draft Web Design Standards themselves.

**Comment by pkarman** [comment]
e-manifest is a Rails app that uses the gem. I think C2 would probably switch as well, when our next redesign is implemented.

**Comment by harrisj** [comment]
Both micropurchase and confidential-survey are using the gem. Just to clarify, under path 2 we would make sure that the RailsEngine in the gem has enough that it needs so that the downstream Rails projects could build their own assets from the SCSS files and such?

**Comment by rogeruiz** [comment]
Yeah @harrisj, the bigger issue around this process would be that the Rails
workflow to sync with the standards would be manual. But the `dist`
directory corresponding to the Rails release would include the necessary
source files and leave bundling to the Rails Asset pipelines. So it would
need to be manually copied into the `vendor` directory.

On Thu, Feb 11, 2016 at 12:43 PM, Jacob Harris notifications@github.com
wrote:

> Both micropurchase and confidential-survey are using the gem. Just to
> clarify, under path 2 we would make sure that the RailsEngine in the gem
> has enough that it needs so that the downstream Rails projects could build
> their own assets from the SCSS files and such?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/us_web_design_standards_gem/issues/15#issuecomment-182972570
> .

## 

Roger Steve Ruiz
804-539-2255
Innovation Specialist @ 18F
General Services Administration
1800 F St. NW, Washington, DC 20405

**Comment by harrisj** [comment]
Understood, I still think we can make this work automatically without a manual copy to the Rails project's `vendor` directory by either [properly configuring the Rails engine](http://guides.rubyonrails.org/engines.html#assets) within the gem or providing a path that calling application can add to the `asset_paths` searched by the asset builder, but we can figure that out later.

**Comment by rogeruiz** [comment]
My thoughts on supporting a Rails version of this `gem`.

We would need the user of the `gem` to have `browserify-rails` in their Gemfile, because of how our JavaScript is written. https://github.com/browserify-rails/browserify-rails

@harrisj I like the idea of rewriting the engine if the level of effort is low enough, meaning we keep one `assets` directory that can contain the source and compiled / bundled assets.

**Comment by mbland** [comment]
Wow, lots of chatter here... Apologies for having created this mess and walking away for so long.

When I created this gem, I naively thought that it'd be straightforward to support both Jekyll (the original use case, based on my experience with the [`guides_style_18f` gem](https://github.com/18F/guides-style/)) and Rails from the same gem. With all the discussion here, and given the prospect of publishing the standards as an npm (18F/web-design-standards#925, 18F/web-design-standards#948), maybe the best route would be:
- Figure out what's needed to get npm publishing of the standards across the finish line; those two issues contain details explaining the different paths we could go by.
- Create a `us_web_design_standards_rails` gem separate from this one.
- Make both gems depend on the npm and incorporate it into their build process via Rake.

This is just an idea, and the folks here have been thinking more deeply about this and are more invested than me at this point. But, what'd'ya think?

Honestly I'm surprised these problems don't appear to yet be solved; or if it has, that news of the solution eludes us. It appears that we're on the verge of establishing another kind of web design standard, in terms of packaging web design standards. :stuck_out_tongue: 

P.S. If you're interested, check out what's happening in 18F/guides-style#49 and 18F/frontend#97. In short, lots of cool new features to support the upcoming Handbook, which incorporates the design standards in Jekyll. I'm hoping to get `guides_style_18f` (18F/guides-style) to depend on this gem for its styles one day.

**Comment by msecret** [comment]
@mbland I like the idea of pulling in the standards with npm in a Rake build task. This would keep compiled code out of the repository. How would this work in terms of versioning?

So if the standards does a match release, lets say from `0.8.1` to `0.8.2`, what will the gem have to do to also be changed? With npm, you can pin a package to a minor or major version, so that small updates automatically get installed, but I'd guess there would still something have to be done for this to work for the gem to get the new changes? When does the Rake task get run? We might want to have the gems version numbers reflect the npm package version's numbers so consumers of the gem could be explicit in what version of standards they want.

I guess somebody would have to manually bump up the version manually when standards does. How would we keep the two in sync?

**Comment by mbland** [comment]
I suppose we could add a script and/or a command to the `./go` script of the 18F/web-design-standards repo that will automatically update the npm and gems. A human would still have to run it, but it'd take the grunt work out of things.

**Comment by rogeruiz** [comment]
@mbland We already have a release process for 18F/web-design-standards using `gulp` which supports builds the contents of this gem as well 18f/web-design-standards#980. I really like your idea of having two gems that ingest our `npm` package. Maybe that's the best way to go once `uswds` is up on `npm` which should be soon when we release `v0.10.0`. :tada:

**Comment by jlev** [comment]
Hey folks, what's the status of this big refactor? I'm using the USDS design standards for voter registration apps for Vote.org, and am trying to decide if I should fork or rely on the main for Rails assets.

Is there a public release timeline somewhere? Thanks for working in the open.

**Comment by juliasolorzano** [comment]
Hello @jlev! The `v0.9.0` release was published last week. Here are the release notes:

https://github.com/18F/web-design-standards/releases/tag/v0.9.0

We also have a public roadmap in our wiki located here, for your reference:

https://github.com/18F/web-design-standards/wiki/Product-Roadmap

As for the development on this gem, it is currently not something the team is actively maintaining. We welcome you to fork and develop for your own usage.

**Comment by pkarman** [comment]
@juliaelman if this gem is no longer maintained, what is the intended support route for design standards w.r.t. Rails and Jekyll sites?

**Comment by juliasolorzano** [comment]
@pkarman great question! We've [updated our README](https://github.com/18F/web-design-standards#using-another-framework-or-package-manager) and have recommendations within those instructions.

**Comment by pkarman** [comment]
@juliaelman thanks for that link. It references https://github.com/18F/web-design-standards/issues/877 which lists this gem. I take it that since @mbland is no longer with 18F, then this gem is orphaned.

Given the number of Ruby-based 18F projects that use or want to use USDS assets, it would be helpful if this gem could get some love. I will circle up with the 18F Ruby devs and see if we can get it going again, using some of the packaging techniques mentioned in this comment thread.

**Comment by juliasolorzano** [comment]
@pkarman excellent! :tada: Please let the team know if the 18F Ruby folks have questions for us.

**Comment by mbland** [comment]
I thought @rogeruiz adopted it from me? @msecret and @juliaelman are also owners: https://rubygems.org/gems/us_web_design_standards

That said, I _do_ have a little time on my hands, and I'd be happy to lend a hand to work out any remaining kinks. Just because I left 18F doesn't mean I've necessarily turned my back on all my open source 18F projects (and I would hope not to be automatically shut out of them, either). Also, when I do get into my next gig, I fully expect to employ this gem, so I do have a little skin in the game.

I'll spend some time this afternoon getting reacquainted with the state of this gem. If anyone wants to create a checklist of specific items that need resolution (sounds like the ideas I sketched out earlier in this thread were agreeable?), I'm happy to pitch in to knock out what I can.

**Comment by jessieay** [comment]
I am a bit confused about what is going on here.

There is this thread about deprecating the gem: https://github.com/18F/us_web_design_standards_gem/pull/19

And then there's a refactor for Jekyll:
https://github.com/18F/us_web_design_standards_gem/pull/18

And there's a refactor for Rails:
https://github.com/18F/us_web_design_standards_gem/pull/7

And then there is the issue we are in now, saying we are officially going to support this gem.

If the plan is to update this gem rather than deprecate, perhaps #19 should be closed.

If this thread is correct, we want to both support Rails and Jekyll.

In the Rails asset fixed PR, @rogeruiz [says](https://github.com/18F/us_web_design_standards_gem/pull/7#issuecomment-182945224): 

> This would be good to merge into master, but I'm hesitant too without more information on whether this gem is considered a Jekyll plugin or a Rails gem and Jekyll plugin

I myself do not know what is needed for a Jekyll plugin. If we can merge both the Jekyll refactor and the Rails refactor and that means this gem works for both, let's do that and release a new version of the gem. I am happy to help with code review, just don't want to get too deep into either PR if the plan is the deprecate this gem.

FWIW, we have several Rails projects floating around at 18F. Used the "rails" fork I have of the gem that includes @harrisj's updates on one and it works great. I'd be thrilled to use this gem on all of my projects if we continue to push it forward.

**Comment by jlev** [comment]
@jessieay, that's why I asked. I'm also using the @harrisj fork on the rails-assets-fixes branch, and basically want to know if I should fork that to add further support, or hope that the main gem will get some love.

**Comment by jessieay** [comment]
@jlev yes, thank you for bringing up this issue!

**Comment by jpyuda** [comment]
The core web design standards/federal front door team is not responsible for maintaining this gem and will not be doing so. It's not used by the team on our projects, and we don't believe it's a need when considering the entirety of our audience (which is not just 18F teams).

If a team that is using the gem would like to support it, I'd encourage that behavior. Otherwise, follow the instructions in the [README](https://github.com/18F/web-design-standards/blob/18f-pages-staging/README.md).

I am aware that in the opening post in this thread Roger said that the USWDS team would be supporting this gem. The decision not to support it was ultimately made by me, and complaints should be sent in my direction.

**Comment by pkarman** [comment]
We have decided to create a Rails-specific gem here: https://github.com/18F/uswds-rails-gem

I suggest we close this ticket as I do not expect any more work to be done on this particular gem. If Jekyll users step forward to revive it, great.
